### ISSUE TITLE
Broken EC links for GO:0102584 & GO:0102585

### ISSUE THREAD

**Issue by youngmip** [geneontology/helpdesk#224]
Dear the GeneOntology team,

The EC links on the following entries are broken:
http://amigo.geneontology.org/amigo/term/GO:0102584
http://amigo.geneontology.org/amigo/term/GO:0102585

Many thanks in advance,
Youngmi

**Comment by kltm** [comment]
Example problematic links are:
http://www.expasy.org/enzyme/2.3.1-
http://www.expasy.org/enzyme/2.4.1-

The metadata transformation originates from:
https://github.com/geneontology/go-site/blob/b1694ab5de6edfc0b3d4fada97cc5f9b366f508c/metadata/db-xrefs.yaml#L634
It would appear then that the ExPASy metadata is out of date. @suzialeksander @pgaudet would you know what the best contact would be to update that? A quick look does not give an obvious new mapping.

**Comment by kltm** [comment]
I would note that the issue here seems to be that ExPASy cannot handle the trailing "-". Is that actually supposed to be there in the definition?

**Comment by suzialeksander** [comment]
@youngmip  Thank you for taking the time to report this bug. You can follow any progress on this ticket if you choose, but we will mention you directly (so you will get an email) in the off chance we need you to provide any more info.  

@kltm  I'm thinking it is, as UniProt cannot handle a search for `ec:2.3.1.` but is satisfied if you leave in the dash: https://www.uniprot.org/uniprot/?query=ec:2.3.1.-

Expasy is also happy to provide a list for `All UniProtKB/Swiss-Prot entries corresponding to class 2.3.1.-.` if you search by EC number from their homepage.

If @pgaudet doesn't have a contact I'll dig around.

**Comment by pgaudet** [comment]
The URLs should be 'https://enzyme.expasy.org/**EC**/1.4.3.6' . I don't think we should use 'search'
(I dont know how to make a branch in GH, so I dont know how to edit this file now...) 

Can someone edit the yaml ? 

Thanks, Pascale

**Comment by kltm** [comment]
Working PR at https://github.com/geneontology/go-site/pull/1131 from @pgaudet

**Comment by kltm** [comment]
@pgaudet Could you please make it so the example URL and the URL giving the syntax are of the same format? As it stands now, the testing URL cannot be generated from the syntax URL.

**Comment by kltm** [comment]
New working PR at https://github.com/geneontology/go-site/pull/1132

**Comment by suzialeksander** [comment]
@kltm when will we know if the PR fixed the issues? I just tried the link on http://amigo.geneontology.org/amigo/term/GO:0102584 and it's still a Not Found.

**Comment by kltm** [comment]
@pgaudet Looking at https://amigo-staging.geneontology.io/amigo/term/GO:0102584 , the generated https://enzyme.expasy.org/EC/2.4.1- is consistent with what is in db-xrefs.yaml, but does not generate a good link. How can determine (or who is the contact) for having the correct links?

**Comment by pgaudet** [comment]
The EC was missing a .dot

Updated: `EC:2.4.1-` -> `EC:2.4.1.-`

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/pull/17615

**Comment by pgaudet** [comment]
Should be fixed; @kltm I leave it to you to check and close ?

**Comment by kltm** [comment]
@pgaudet That would seem to fix it. I've moved this item into `Clearing` so it can be checked after the next `release` (or tested `snapshot`).

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/pull/17619

**Comment by suzialeksander** [comment]
update: still not fixed, waiting on next release to check again.

**Comment by suzialeksander** [comment]
Yay! working as of today.  Closing as resolved.
